# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

for_loop_idm <- function(resolution, n, time_length, s_0, Tg, a, b, v_0, small_delta, ln1, Time, vn, vn1, sn_star, sn, xn, xn1, deltav, v_dot) {
    .Call(`_carfollowingmodels_for_loop_idm`, resolution, n, time_length, s_0, Tg, a, b, v_0, small_delta, ln1, Time, vn, vn1, sn_star, sn, xn, xn1, deltav, v_dot)
}

for_loop_gipps <- function(resolution, n, time_length, tau, an, bn, Vn, bcap, ln1, Time, vn_ff, vn_cf, vn, vn1, sn, xn, xn1, deltav, bn_v) {
    .Call(`_carfollowingmodels_for_loop_gipps`, resolution, n, time_length, tau, an, bn, Vn, bcap, ln1, Time, vn_ff, vn_cf, vn, vn1, sn, xn, xn1, deltav, bn_v)
}

for_loop_wiedemann <- function(D_MAX, time_length, BXadd, AX, CX, EX, OPDVadd, BMAXmult, V_MAX, FaktorV, BMIN, BNULL, resolution, vn, vn1, sn, xn, xn1, deltav, bn1) {
    .Call(`_carfollowingmodels_for_loop_wiedemann`, D_MAX, time_length, BXadd, AX, CX, EX, OPDVadd, BMAXmult, V_MAX, FaktorV, BMIN, BNULL, resolution, vn, vn1, sn, xn, xn1, deltav, bn1)
}

